- name: download files elastic
  shell: |
    wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.16.2-linux-x86_64.tar.gz
    tar -xvzf elasticsearch-7.16.2-linux-x86_64.tar.gz
    
- name: edit config file
  lineinfile:
    destfile: elasticsearch-7.16.2/config/elasticsearch.yml
    # Line to Search/Match against
    regexp: "{{ item.From }}"
    # Line to Replace with
    line: "{{ item.To }}"
    state: present 
  with_items:
    - { From: '#network.host: 192.168.0.1', To: 'network.host: {{ elastic_host }}'}
    - { From: '#discovery.seed_hosts: ', To: 'discovery.seed_hosts: []'}
    - { From: '#cluster.initial_master_nodes: ', To: 'cluster.initial_master_nodes: ["{{ elastic_host }}"]'} 

- name: install java
  apt:
    name: default-jdk
    update_cache: yes

#- name:
#  shell: 
#    cmd: ./bin/elasticsearch
#    chdir: elasticsearch-7.16.2
  

- name: Update Max Memory
  shell: sysctl -w vm.max_map_count=262144

- name: download files kibana
  shell: |
    wget https://artifacts.elastic.co/downloads/kibana/kibana-7.16.2-linux-x86_64.tar.gz
    tar -xvzf kibana-7.16.2-linux-x86_64.tar.gz
    
- name: edit config files
  lineinfile:
    destfile: kibana-7.16.2-linux-x86_64/config/kibana.yml
    # Line to Search/Match against
    regexp: "{{ item.From }}"
    # Line to Replace with
    line: "{{ item.To }}"
    state: present 
  with_items:
    - { From: '#server.host: "localhost"', To: 'server.host: 0.0.0.0'}
    - { From: '#elasticsearch.hosts: ["http://localhost:9200"]', To: 'elasticsearch.hosts: ["http://{{ elastic_host }}:9200"]'} 


- name: permissions elastic
  shell:
    cmd: chmod -R 777 elasticsearch-7.16.2/

- name: permissions kibana
  shell:
    cmd: chmod -R 777 kibana-7.16.2-linux-x86_64/


#- name:
#  shell:
#    cmd: ./bin/kibana
#    chdir: cd kibana-7.16.2-linux-x86_64