- hosts: localhost
  connection: local
  vars_files:
    - vars.yml
  tasks:
    - name: create a instance
      google.cloud.gcp_sql_instance:
        name: "{{ sql_name }}"
        database_version: "POSTGRES_14"
        settings:
          ip_configuration:
            authorized_networks:
            - name: google dns server
              value: 0.0.0.0/0
          tier: db-custom-2-7680
        region: "{{ region }}"
        project: "{{ project }}"
        auth_kind: "{{ auth_kind }}"
        service_account_file: "{{ file }}"
        state: present
      register: instance

    - name: create a user
      google.cloud.gcp_sql_user:
        name: "{{ db_username }}"
        host: ""
        password: "{{ db_password }}"
        instance: "{{ instance }}"
        project: ascn-330814
        auth_kind: serviceaccount
        service_account_file: "./service.json"
        state: present

    